create table xxpc_approvals (
    approval_id         number generated by default on null as identity,
    entity_name         varchar2(30) not null,
    entity_id           number not null,
    approver_user_name  varchar2(100) not null,
    sequence_num        number default 1 not null,
    status_code         varchar2(30) default 'PENDING' not null,
    comments            varchar2(1000),
    action_date         date,
    created_by          number,
    creation_date       date default sysdate not null,
    last_updated_by     number,
    last_update_date    date default sysdate not null,
    constraint xxpc_approvals_pk primary key (approval_id),
    constraint xxpc_approvals_entity_ck check (entity_name in ('REQUEST', 'EXPENSE')),
    constraint xxpc_approvals_status_ck check (status_code in ('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED'))
);
