create table xxpc_attachments (
    attachment_id   number generated by default on null as identity,
    entity_name     varchar2(30) not null,
    entity_id       number not null,
    file_name       varchar2(255) not null,
    mime_type       varchar2(255),
    file_content    blob,
    file_url        varchar2(1000),
    uploaded_by     number,
    uploaded_date   date default sysdate not null,
    constraint xxpc_attachments_pk primary key (attachment_id),
    constraint xxpc_attachments_entity_ck check (entity_name in ('REQUEST', 'EXPENSE'))
);
