create table xxpc_audit_log (
    audit_id          number generated by default on null as identity,
    entity_name       varchar2(30) not null,
    entity_id         number not null,
    action_code       varchar2(30) not null,
    old_status_code   varchar2(30),
    new_status_code   varchar2(30),
    action_by         number,
    action_date       date default sysdate not null,
    comments          varchar2(1000),
    constraint xxpc_audit_log_pk primary key (audit_id)
);
