create table xxpc_categories (
    category_id        number generated by default on null as identity,
    category_code      varchar2(30) not null,
    category_name      varchar2(120) not null,
    account_ccid       number,
    taxable_flag       varchar2(1) default 'N' not null,
    receipt_required   varchar2(1) default 'Y' not null,
    active_flag        varchar2(1) default 'Y' not null,
    created_by         number,
    creation_date      date default sysdate not null,
    last_updated_by    number,
    last_update_date   date default sysdate not null,
    constraint xxpc_categories_pk primary key (category_id),
    constraint xxpc_categories_u1 unique (category_code),
    constraint xxpc_categories_tax_ck check (taxable_flag in ('Y', 'N')),
    constraint xxpc_categories_receipt_ck check (receipt_required in ('Y', 'N')),
    constraint xxpc_categories_active_ck check (active_flag in ('Y', 'N'))
);
