create table xxpc_requests (
    request_id          number generated by default on null as identity,
    request_number      varchar2(30) not null,
    pc_user_id          number not null,
    request_date        date default sysdate not null,
    requested_amount    number(15,2) not null,
    approved_amount     number(15,2),
    currency_code       varchar2(15) default 'AED' not null,
    purpose             varchar2(1000),
    status_code         varchar2(30) default 'DRAFT' not null,
    ap_invoice_id       number,
    payment_reference   varchar2(240),
    submitted_date      date,
    approved_date       date,
    rejected_date       date,
    closed_date         date,
    created_by          number,
    creation_date       date default sysdate not null,
    last_updated_by     number,
    last_update_date    date default sysdate not null,
    constraint xxpc_requests_pk primary key (request_id),
    constraint xxpc_requests_u1 unique (request_number),
    constraint xxpc_requests_user_fk foreign key (pc_user_id) references xx_users (pc_user_id),
    constraint xxpc_requests_amount_ck check (requested_amount > 0),
    constraint xxpc_requests_status_ck check (
        status_code in ('DRAFT', 'SUBMITTED', 'APPROVED', 'REJECTED', 'PAID', 'CLOSED', 'CANCELLED')
    )
);
